spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 12345
     #username: 
     #password: 
      database: test
     #uri: mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test